version: '3.8'
services:
  web_app:
    image: web_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
    driver: overlay
